file:
  upload-dir: C:/Users/sany/uploads/

server:
  port: 9000

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ecom_Db
    username: postgres
    password: samy
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  web:
    resources:
      static-locations: file:C:/Users/sany/uploads/
  mvc:
    static-path-pattern: /uploads/**

  security:
    oauth2:
     resourceserver:
       jwt:
        issuer-uri: http://localhost:8083/realms/ecom-realm
jwt:
  auth:
    converter:
      resource-id: ecom-api
      principal-attribute: preferred_username





