
server:
  port: 9000


spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ecom_Db
    username: posgresql
    password: samy
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  security:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8081/realms/ecom-realm
        jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource_id: ecom-api
      principal-attribute: preferred_username




