file:
  upload-dir: C:/Users/sany/Uploads/

server:
  port: 9000

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ecom_Db
    username: postgres
    password: samy
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  security:
    oauth2:
     resourceserver:
       jwt:
        issuer-uri: http://localhost:8081/realms/ecom-realm
jwt:
  auth:
    converter:
      resource_id: ecom-spring
      principal-attribute: preferred_username





