services:
  postgres:
    image: postgres
    container_name: postgres-sql-ecom
    environment:
      POSTGRES_DB: e-commerceDb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-demo

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    container_name: keycloakEcom
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    command:
      - "start-dev"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local